### ISSUE TITLE
vesion SSL

### ISSUE THREAD

**Issue by noiwid** [kmmndr/reboot-fbx#1]
Bonjour,
Je chercher à utiliser votre script, mais avec les URL's HTTPS, je n'y parviens pas.
Avez-vous une version plus récente de votre script qui intégrerai le passage en https ? 
Merci d'avance pour votre retour.

**Comment by kmmndr** [comment]
Bonjour @noiwid
Je viens de mettre à jour l'outil pour ajouter le support du protocole https.
Merci d'utiliser cet outil :-)

**Comment by noiwid** [comment]
Bonjour,
merci pour le retour :)
Ma freebox est installée sur un domaine personnalisé, est-il possible d'utiliser ce script à distance (ie : installé sur un serveur web par exemple), ou il faut impérativement être en local sur la freebox concernée pour que cela fonctionne ?

**Comment by kmmndr** [comment]
En effet, il faudra que le script soit démarré sur le réseau de la Freebox pour que ça fonctionne
