### ISSUE TITLE
Erreur: status unknow

### ISSUE THREAD

**Issue by zbugrkx** [kmmndr/reboot-fbx#3]
Bonjour,

je tente ma chance en espérant que ce projet n’est pas abandonné !

lors de l’installation j’ai été trop lent pour valider la demande d’association sur la box, résultat impossible de faire une nouvelle demande malgré reboot etc. J’ai supprimé la demande ratée depuis l’interface de la box aussi mais rien n’y fait.

Toujours l’erreur suivante :

`sudo ./reboot-fbx 
api_version: 9.1
track_id: 2
waiting.
Error: status unknown `

Une idée ?

merci!

cordialement

**Comment by kmmndr** [comment]
Rassurez-vous, il n'est pas abandonné.

Vous avez certainement dû avoir un message comme celui-ci lorsque vous aviez effectué le premier démarrage :

```
$ reboot-fbx
api_version: 8.5
track_id: 0
waiting...........................................................................
Error: status timeout
```

Et vous obtenez désormais l'erreur `Error: status unknown` puisque vous avez supprimé la demande ratée dans l'interface de la Freebox.

Il suffira donc de refaire une toute nouvelle demande depuis votre ordinateur, pour cela supprimez le fichier de configuration (par défaut ~/.reboot-fbx.conf)

```
rm ~/.reboot-fbx.conf
```

Et de relancer la procédure au début, en marchant un peu plus vite cette fois-ci :-)

N'hésitez pas à me solliciter si vous recontrez d'autres problèmes.

**Comment by zbugrkx** [comment]
Merci beaucoup de vôtre retour rapide et ravis de savoir que c'est toujours suivi :)

C'est exactement ce qu'il me manquait! (peut-être une bonne idée d'indiquer l'info dans le readme?

Encore merci!
Cordialement,

**Comment by Adelscott** [comment]
C'est la même procédure lorsqu'on vous fait un échange de Freebox, il faut supprimer le fichier sinon on arrive directement à "Error: status unknown"
